# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
git:
    depth: 99999999
after_success:
  - julia -e 'cd(Pkg.dir("uJSON")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("uJSON")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

